-- TODO: restrict efm-langserver to operate only on desired projects.
--       e.g. when you are exploring a project
--       but don't want to mess its formatting
--       or in projects you want to contribute
--       but don't own or when the project
--       doesn't follow the same style guide
--       as you.
--       SEE: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#conditional-sources

-- TODO: setup vint (viml) diagnostics
-- TODO: setup selene diagnostics
-- TODO: setup shellcheck diagnostics
-- TODO: setup flake8 diagnostics
-- TODO: setup tidy diagnostics
-- TODO: setup checkmake diagnostics (make linter)
