-- TODO: make pkgbuild shellcheck lint work

-- local null_ls = require "null-ls"
-- local helpers = require "null-ls.helpers"
--
-- local pkgbuildlint = {
--   method = null_ls.methods.DIAGNOSTICS,
--   filetypes = { "pkgbuild" },
--   generator = null_ls.generator {
--     command = "shellcheck",
--     args = { "--format", "json1", "--source-path=$DIRNAME", "--external-sources", "-" },
--     to_stdin = true,
--     format = "json",
--     check_exit_code = function(code)
--       return code <= 1
--     end,
--     on_output = function(params)
--       local parser = helpers.diagnostics.from_json {
--         attributes = { code = "code" },
--         severities = {
--           info = helpers.diagnostics.severities["information"],
--           style = helpers.diagnostics.severities["hint"],
--         },
--       }
--
--       return parser { output = params.output.comments }
--     end,
--   },
-- }

-- null_ls.register(pkgbuildlint)
